version: '3.8'

services:

  script:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: username
      POSTGRES_DB: database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432